# Generated by Django 5.2.6 on 2026-05-19 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0002_alter_cuentacorriente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadiaria',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha'),
        ),
    ]
