# Generated by Django 5.2.6 on 2026-05-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0003_alter_ventadiaria_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorriente',
            name='tipo_movimiento',
            field=models.CharField(choices=[('DEUDA', 'Compra fiada'), ('PAGO', 'Entrega de dinero')], default='DEUDA', max_length=10),
        ),
    ]
