# Generated by Django 5.2.6 on 2026-07-23 16:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0004_alter_cuentacorriente_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadiaria',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='despensa.cliente'),
        ),
        migrations.AddField(
            model_name='ventadiaria',
            name='operacion_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='identificador de operación'),
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=160)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_vendidos', to='despensa.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='despensa.ventadiaria')),
            ],
            options={
                'verbose_name': 'artículo de venta',
                'verbose_name_plural': 'artículos de venta',
                'ordering': ['id'],
            },
        ),
    ]
